[package]
name = "dither"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = "*"
embedded-graphics-core = "*"

[dev-dependencies]
embedded-graphics = "0.8.1"
embedded-graphics-simulator = "0.6.0"
tinybmp = "0.5.0"
