name: CI Checks

on: [push, pull_request]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CARGO_TERM_COLOR: always

jobs:
  std:
    name: build, clippy, fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update
      - run: sudo apt-get install libsdl2-dev
      - run: cargo build --all-features
      - run: cargo clippy --all-features
      - run: cargo fmt -- --check
  release:
    if: github.ref_type == 'tag'
    name: create github release from updated tags
    runs-on: ubuntu-latest
    needs: [std]
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: ncipollo/release-action@v1
